### ISSUE TITLE
Need a way to make Geckoview/webview default for UI tests

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#3335]
### Why/User Benefit/User Problem
Right now Klar Debug build variants use webview as default, and we cannot run UI tests on Geckoview, since they will run on debug only.  None of the UI tests are running on Geckoview at this moment I believe.

### What / Requirements
We need a way to make geckoview default, in order to run ui tests on geckoview variant, if we consider running UI tests on Geckoview a must.

@colintheshots thoughts?

**Comment by npark-mozilla** [comment]
What used to happen is that within the UI test , it sets the sharedpref, (as seen in: https://github.com/mozilla-mobile/focus-android/blob/master/app/src/androidTest/java/org/mozilla/focus/activity/AccessSettingsTest.java#L54) but according to Colin, this would no longer work.  We need to somehow set it through the Fretboard.

**Comment by colintheshots** [comment]
There's two potential solutions:
- Use Fretboard setOverride() calls to set the shared preference Fretboard uses to override any value from the network or disk. It probably doesn't have to be the same instance of Fretboard that the app uses, since the shared preferences file name Fretboard uses is fixed and static.
- Directly edit the shared preferences that Fretboard uses. This may not be as future-proof in case Fretboard changes the way it persists overrides. That preferences file is "mozilla.components.service.fretboard.overrides" and the preference name is the same as the experiment name "use-gecko" or "use-gecko-nightly" in Nightly.

**Comment by npark-mozilla** [comment]
@colintheshots seems like instantiating Fretboard is a lot of work within the ui test script - if I want to directly edit the shared pref file, would it be similar as before?  I tried
<PreferenceManager.getDefaultSharedPreferences(appContext)
                        .edit()
                        .putBoolean(EXPERIMENT_DESCRIPTOR_GECKOVIEW_ENGINE, true)
                        .apply()>
but this did not work.

**Comment by npark-mozilla** [comment]
Also tried 
```
 ((FocusApplication)appContext).fretboard.setOverride(appContext,
                        new ExperimentDescriptor(Config.EXPERIMENT_DESCRIPTOR_GECKOVIEW_ENGINE),
                        true);
```
This should have worked i think, but if I go to about focus menu, it still doesn't display the geckoview logo.

**Comment by npark-mozilla** [comment]
I think it's best if a dev can take over this issue.

**Comment by reno-a** [comment]
Hello,
Just a question : why GeckoView and not QuantumView (new engine name)?

**Comment by colintheshots** [comment]
So, there's two issue here. First, I added a blocking API because Fretboard.setOverride() is asynchronous. Try Fretboard.setOverrideNow() instead.

If you assert the engine is Gecko or WebView at the very start of the test, it'll still be null, however. It takes some time for the engine to get picked now that we have a blocking disk read to set the engine based on the experiments on disk at the time.
