### ISSUE TITLE
Show information about SSL certificate

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#454]
To fix this bug implement the mocks that @brampitoyo provides. See https://github.com/mozilla-mobile/focus-android/issues/454#issuecomment-304553461 and later comments.

Please note this is slated for v5.0 and will need to be completed by mid-Februrary, according to [the current calendar](https://wiki.mozilla.org/Mobile/Focus/Android/Train_Schedule).

---

From feedback:

> Seems like I cannot view SSL cert info. Pressing the lock icon in Fennec Android shows some info.

![cert](https://cloud.githubusercontent.com/assets/89638/24998768/926be0d2-203b-11e7-856f-a79a867e8841.jpg)

**Comment by ahunt** [comment]
Here's a V1, I've just followed the fennec design for now.
![doorhanger_v1](https://cloud.githubusercontent.com/assets/1546915/25966646/73579ee6-3640-11e7-9330-8146888ac90f.png)

I'm wondering if we should we just use the default material icon (we can use that in the toolbar too?): https://material.io/icons/#ic_lock

AFAICT we can't access EV certificate information when using WebView, at least not without some horrible hacks...
https://developer.android.com/reference/android/net/http/SslCertificate.html
We can get the underlying cert using:
http://stackoverflow.com/a/35858045
And then AFAUI we'd need to manually parse the X509 cert to get EV information.

(It looks like even Chrome doesn't bother with showing EV status on Android, Firefox however does show EV status.)

**Comment by ahunt** [comment]
Here's another screenshot if we don't show the doorhanger over the lock button (which is non-materialy, but probably better in this case?):
![doorhanger_v2](https://cloud.githubusercontent.com/assets/1546915/26010943/d280f4f8-3703-11e7-9998-b78b43929b68.png)

I don't know if showing the issued to "CName" is the right thing for the doorhanger, it looks like Firefox shows the site hostname instead (the CName could be a different host, e.g. when sumo was running on lithium the cert/CName was for something.lithium.com, and support.mozilla.org was one of the alternate domains in the cert).

@antlam: do you have any ideas/designs for the site security doorhanger?

**Comment by pocmo** [comment]
This is not v1 and not nice-to-have though! :)

**Comment by ahunt** [comment]
I guess my main concern is that in most browsers, we're trying to teach users to check when sites are encrypted by using the green lock icon, but in focus we're breaking that expecation. (I wonder whether it would be considered good UX to also show a broken padlock for http sites? And should we be using a green padlock to be consistent with most other browsers.) Either way, that's for product/UX to decide!

See e.g. https://support.mozilla.org/en-US/kb/how-do-i-tell-if-my-connection-is-secure for what I think users might expect.
(I don't know if it's even possible for us to check for mixed content with WebView, so we probably can't even do that part...).

**Comment by pocmo** [comment]
I agree with your sentiment in general - however we have triaged this before and decided to not pick it up for v1. Feel free to flag it for triage and we can re-discuss though!

**Comment by ahunt** [comment]
Not V1, but I'll push my branch somewhere for whenever we want to build this.

**Comment by ahunt** [comment]
(My branch is at https://github.com/mozilla-mobile/focus-android/tree/ahunt/sslui - it still needs contentDescriptions added and UX feedback)

**Comment by antlam** [comment]
@brampitoyo thoughts? (not for V1 :) )

**Comment by brampitoyo** [comment]
Hey! This is an area that matches my expertise :-)

There are 4 different site states that we’ll need to design for. Here they are, along with accompanying info text:

#### Secure HTTPS (icon: green lock)

##### A. SSL
domainname.net
<green>Secure Connection</green>

##### B. SSL EV
domainname.net
<green>Secure Connection</green>
Verified by: Cert Authority, Inc. (US)

#### No HTTPS – in other words, HTTP (icon: none, or grey globe)
domainname.net
<red>Connection is Not Secure</red>

#### Bad HTTPS (icon: grey lock with yellow warning sign)
domainname.net
<red>Connection is Not Secure</red>

We can consider adding explanatory captions like “You should not reveal your personal information (like passwords or credit cards) on this site, because it can be stolen.” later. For now, designing for these states with helpful info texts is what’s important.

**Comment by brampitoyo** [comment]
### Doorhangers

![site-info-doorhangers](https://cloud.githubusercontent.com/assets/51007/26534686/7f12fbfa-4472-11e7-851a-540dcd8689be.png)

### URL bar icons

I feel conflicted about adding any colour to the URL bar icon, because it’s visually distracting. My proposed solution is to make all the site status icons white. When you tap on it to get more info, then we’ll show some colours, as above.

![site-info-url-bar-indicators](https://cloud.githubusercontent.com/assets/51007/26534700/a2cdfe82-4472-11e7-9414-d46cf3b3afb0.png)

Thoughts?

**Comment by antlam** [comment]
nice! I like where this is going. We should look to align with Photon iconography as well when we get to this.

**Comment by brampitoyo** [comment]
Photon site info icons

<img width="1614" alt="screen shot 2017-05-30 at 4 58 45 pm" src="https://cloud.githubusercontent.com/assets/51007/26570000/b94a04de-4559-11e7-9371-98f514409739.png">

Replaced the lock icon with the one used on desktop Photon.

The yellow warning sign was also directly taken off desktop Photon.

I wasn’t able to find a Photon take on the globe icon, so I had to recreate it by combining the Photon circle with the old continent shapes. It doesn’t look as good as the other ones. We’ll think of something else.

**Comment by pocmo** [comment]
Overall this looks pretty good to me. :)

(I'm a bit hesitant to think too much about non v1 issues this close to release now - there's no clear roadmap yet)

**Comment by brampitoyo** [comment]
Sounds good, @pocmo. I’ve tagged this issue `post-v1`, so we don’t have to worry about it now. Let’s continue to refine it when necessary.

**Comment by mcomella** [comment]
@brampitoyo Are the UX mocks in this bug final? I wonder if we can get this to our contributors.

**Comment by brampitoyo** [comment]
The interaction is final, but the visual design – specifically, colour values – need to be tweaked ever so slightly, to conform to Photon.

<img width="1626" alt="screen shot 2017-10-26 at 4 47 35 pm" src="https://user-images.githubusercontent.com/51007/32034173-7daf8da2-ba6d-11e7-8b1d-cd8eeb79c710.png">

The green value we use for the icon and text is `green-60` `#12bc00`, and the icon is called `Identity Secure`. Unfortunately, the icon you find on the Photon Icon Library is outdated, but Firefox for Desktop already uses the new green lock SVG, with slightly different proportion. Use this one instead.

The red value for the text is `red-60` `#d70022`, and the world icon is called `Identity Not Secure`. The icon is outdated, but it’s all we have at the library, so let’s use it for the time being.

And the yellow value for the warning icon is `yellow-60` `#d7b600`, and the icon is called `warning-16`.

Hope this helps!

**Comment by ahunt** [comment]
Happy to take this on since this bugs me occasionally.

IIRC WebView doesn't actually provide data for EV certificates, but I'll check that again - perhaps that's been fixed in more recent WebView (and/or we can try adding it directly ourselves : ) ).

**Comment by ekager** [comment]
Hi @ahunt , did you end up starting work on this, or should I take it over?

**Comment by ekager** [comment]
@brampitoyo wondering if any of these icons need updating from previously specified from the Photon library, etc?

**Comment by brampitoyo** [comment]
@ekager As far as I’m aware, our icon situation is still the same as October. Maybe it will help to have a look at the icons that Firefox for Android uses, and use them for our own design?

**Comment by brampitoyo** [comment]
After talking with @ekager, we’ve decided to follow Fennec’s SSL info modal design instead of implementing our own (circa October 2017).

When we started this project, Fennec didn’t have a Photonised design. We wanted to look forward, so have came up with the designs above. Since then, Fennec had been redesigned from the ground up. This included the SSL info modal. For consistency and simplicity, we should follow it.

The only thing we will do differently is to **use a dark background for the modal** (Fennec uses light). Everything else (icons, spacing, copy, etc.) should follow Fennec.

**Comment by pocmo** [comment]
> Hi @ahunt , did you end up starting work on this, or should I take it over?

With out current timeline I guess it's pretty safe to take this over. There are two commits linked above. Maybe they are helpful: 4776404eb2d1ee682075ab49569bdb8cbe0eeb41 4955a361c4476ab6bdd5e9cb717cc58a75a57a8f.

I wonder if we can get everything we need for this dialog from WebView. On IRC snorp mentioned that onSecurityChange() should provide this data in GeckoView.

> @ekager As far as I’m aware, our icon situation is still the same as October. Maybe it will help to have a look at the icons that Firefox for Android uses, and use them for our own design?

Do we have vector images for those? Afaik in Fennec we still use PNGs mostly (Maybe this changed with the redesign though).

**Comment by brampitoyo** [comment]
> Do we have vector images for those? Afaik in Fennec we still use PNGs mostly (Maybe this changed with the redesign though).

Yes, we do. I’ve given the link to our Fennec SVG folder to @ekager in a DM.

**Comment by ekager** [comment]
Tagging @brampitoyo for quick review of the three states

![screenshot_20180302-153957](https://user-images.githubusercontent.com/25442310/36927166-a238b712-1e30-11e8-8740-b74f2f44f09f.png)
![screenshot_20180302-153932](https://user-images.githubusercontent.com/25442310/36927169-a4124e68-1e30-11e8-9afe-60146f65759d.png)
![screenshot_20180302-154124](https://user-images.githubusercontent.com/25442310/36927170-a5d2bcba-1e30-11e8-8b3b-7ea37da704f4.png)

**Comment by brampitoyo** [comment]
Hi Emily, you’re on the right track! Just a few items to note, so we can match Fennec’s style a bit more:

![fennec-vs-focus-ssl-info 2x](https://user-images.githubusercontent.com/51007/36950988-f5932c7e-2062-11e8-9d4e-61b9d7dbe509.png)

1. Fennec’s warning icon on the toolbar is slightly smaller than ours.
2. After adding exception, our SSL modal seems to be missing a text that says “You have added a security exception…”. But last week, you wrote that Focus doesn’t yet have an ability to add an exception – perhaps I’m misunderstanding.
3. Our warning and checkbox icons inside the SSL modal seems to have a 24dp dimension. Fennec’s icon: 16dp.
4. Fennec’s SSL modal has a fixed width with equal 32dp side margins. We have a flexible width with 16dp left margin.
5. Fennec’s SSL modal has more top margin (I measured 46dp, but could be wrong) than ours (41dp)
6. When Fennec’s SSL modal is opened, the website background is dimmed with a transparent grey overlay. Ours aren’t dimmed.

Hope these changes aren’t tricky to make!

**Comment by ekager** [comment]
![screenshot_20180306-163633](https://user-images.githubusercontent.com/25442310/37067154-64cf6f62-215d-11e8-9bda-e8c3794ecd84.png)
![screenshot_20180306-163714](https://user-images.githubusercontent.com/25442310/37067156-6692b570-215d-11e8-835b-04f6c4e82ffc.png)
![screenshot_20180306-163646](https://user-images.githubusercontent.com/25442310/37067158-6883dea4-215d-11e8-86af-53d6db295d92.png)

Hi @brampitoyo , I've made some changes to the popup. 

The warning icon may look bigger but the ImageView is set to 24dp x 24dp so I'm not sure why it would be bigger... It may just be a more square icon so looks bigger, but I could add a bit of padding when this icon is displayed if this is not acceptable?

In terms of the shadow I'm using 4dp elevation that follows the style of the popup menu. 

You cannot add a security exception for sites with insecure connections. The page will just not load and you will get an error. So there is no exception text?

**Comment by brampitoyo** [comment]
> The warning icon may look bigger but the ImageView is set to 24dp x 24dp so I'm not sure why it would be bigger...

Thanks a lot for looking into this! Maybe it’s possible that the SVG used on Fennec has a bigger margin? Anyway, we shouldn’t change anything from our end. Let’s keep the dimension that’s already in use today.

> In terms of the shadow I'm using 4dp elevation that follows the style of the popup menu.

I hope it’s not just my sights, but I still can’t see the shadow. I reckon this may just be the quirk of the simulator, and the end result would look alright.

> You cannot add a security exception for sites with insecure connections.

Right. So then, on this particular scenario, let’s change the grey lock icon on the left-hand side of the modal to a yellow warning sign.

<img src="https://user-images.githubusercontent.com/51007/37071362-0e4fbe0c-2221-11e8-83f6-7a10439e3848.png" width="360">

**Comment by ekager** [comment]
Thanks @brampitoyo ! Made that change and I also figured out the shadow issue. :)
