### ISSUE TITLE
Cookies aren't blocked when "Block 3rd-party cookies only" is selected

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#4740]
## Steps to reproduce
1. Go to three-dot menu: Settings ->  Privacy & Security -> Cookies and Site Data -> Blocked Cookies and select "Block 3rd-party cookies only".
2. Go to: https://rpappalax.github.io/testapp and tap on "Are cookies enabled?" from the Blocked Cookies Test area.

### Expected behavior
The whatismybrowser.com answers "No" (aka: Cookies are blocked).

### Actual behavior
The whatismybrowser.com answers "Yes".

### Device information
* Android device: Google Pixel (Android 10)
* Focus version: build from master (1186.0.1- 20210310152336)
* Not reproducible on Focus 8.14.0 with Google Pixel 2 (Android 9)
* Reproducible also when "Block 3rd-party tracker cookies only" is selected.

**Comment by pocmo** [comment]
Nominating this to get added to the staging / planning board.

**Comment by pocmo** [comment]
@Amejia481 If you have a bit of time, do you see any obvious mistake we made when hooking up this setting?

**Comment by pocmo** [comment]
(The default option not being selected in settings is a known issue and tracked here: #4341)

**Comment by Amejia481** [comment]
No problem, I will try to take a look today.

**Comment by Amejia481** [comment]
It looks like it's related to [this new API,](https://bugzilla.mozilla.org/show_bug.cgi?id=1700750) that separates how cookies behave on private browsing, before the same setting controlled both, now we have to expose the new API to be able to control private browsing cookies, this will be covered here https://github.com/mozilla-mobile/android-components/issues/10126.  

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/773158/116328072-2b667500-a796-11eb-8064-6d4380f2c594.png">

The same issue is on Fenix but as Focus is always on private browsing gets affected directly, I have to bump the priority, to covered the AC ticket.

**Comment by Amejia481** [comment]
The issues was addressed on https://github.com/mozilla-mobile/android-components/commit/429f8390559bfdac7a01f10c81b4231cfe71fa68, now the cookie behavior in private mode is following the same value as the cookie behavior in normal mode, unless we spesific a value for private mode. The change will be reflected on Focus when we update to the latest AC version.

**Comment by lobontiumira** [comment]
This issue reproduces with the "Block 3rd-party cookies only", and with the "Yes" options enabled from Settings -> Privacy & Security -> Cookies and Site Data -> Blocked Cookies.
Tested on 8.16.0 Focus build with Google Pixel (Android 10).

**Comment by Amejia481** [comment]
The fix will be available when Focus updates to AC `90.0.20210527190029` or above :)

**Comment by lobontiumira** [comment]
This issue still reproduces with 8.17.0 with GeckoView 90.0.20210705185941 and AC 90.0.12, with OnePlus 5T (Android 10).

**Comment by Amejia481** [comment]
> This issue still reproduces with 8.17.0 with GeckoView 90.0.20210705185941 and AC 90.0.12, with OnePlus 5T (Android 10).

Thanks for testing @lobontiumira,

Reading from the [STR](https://github.com/mozilla-mobile/focus-android/issues/4740#issue-835799062):

> 2. Go to: https://rpappalax.github.io/testapp and tap on "Are cookies enabled?" from the Blocked Cookies Test area.

In the step 2, we should be checking for the option "**Are 3rd Party Cookies Enabled?"** as we are changing the setting  **"Block 3rd-party cookies only"** :).

**Comment by lobontiumira** [comment]
@Amejia481 it is reproducible also when "Block 3rd-party tracker cookies only" is selected.

**Comment by Amejia481** [comment]
Which site are you using for testing?

**Comment by lobontiumira** [comment]
On https://rpappalax.github.io/testapp

**Comment by Amejia481** [comment]
I think there is confusing in the terminology the option is called "Block 3rd-party **tracker cookies** only" and the site that we are using for testing is checking for **Third-Party Cookies**. No all **Third-Party Cookies** are **trackers**.

The expected behavior should be:

- The option "**Block 3rd-party tracker cookies only"** should say **YES**.
- The option **"Block 3rd-party cookies only"** should be **NO**.

In the latest, main branch I'm able to get the expected behavior above, I'm checking why the results are different on the build that you are testing on I think is based on tag [v8.17.0](https://github.com/mozilla-mobile/focus-android/releases/tag/v8.17.0), I will report back.

**Comment by Amejia481** [comment]
Chatting with @jonalmeida, he commented that tag  [v8.17.0](https://github.com/mozilla-mobile/focus-android/releases/tag/v8.17.0) is using a custom GV version, that explains the behavior difference, for this bug we should only test on `main` as the  [v8.17.0](https://github.com/mozilla-mobile/focus-android/releases/tag/v8.17.0) version is based on the `release` branch and we aren't going to use that code any more. It's a maintenance branch that we've been using to cut our releases.

**Comment by lobontiumira** [comment]
I've retest on a maine build 8.13.1 (1191.0a1-20210705095222) on an emulator, and the issue no longer reproduces.
I'll close this issue, based on my findings, and on the explanations provided by Arturo.
