### ISSUE TITLE
Ads, social and analytics trackers aren't blocked with default settings

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#4864]
## Steps to reproduce
1. With default TP settings, go to https://senglehardt.com/test/trackingprotection/test_pages/tracking_protection.html
2. Check ads, social and analytics trackers
3. Go to Settings>Privacy
4. Enable the "Block other content trackers" option too.
5. Refresh the TP test page.
6.  Check ads, social and analytics trackers
### Expected behavior
The 3 categories should be blocked by default.
### Actual behavior
Step 2: the 3 trackers appear as Not Blocked.
Step 6: the 3 categories are shown as being blocked only after enabling the "other content" category which shouldn't be required.
### Device information

* Android device: Pixel 2, Android 10
* Focus version: Debug 8.13.1 (Build #1190.0a1-20210426094327)
* Not reproducing on Release 8.15.3

**Comment by pocmo** [comment]
This is with a build from `master`?

**Comment by sv-ohorvath** [comment]
> This is with a build from `master`?

Yes, from *main*.

**Comment by pocmo** [comment]
Oh, yes `main` :)

@Amejia481 Do you have time to help us debug this?

**Comment by Amejia481** [comment]
Sure :) 
I can take a look after I finish with the site permissions migration work.

**Comment by Amejia481** [comment]
This will be covered by https://github.com/mozilla-mobile/focus-android/pull/4911.
Just to let you know, there is a known bug for fresh installs, where we are not able to block on the first load as it take some time for geckoView to fetch and download the content blocking list, if that happens refreshing should fix the issue and all subsequent loads should be blocked, see https://github.com/mozilla-mobile/fenix/issues/7907#issuecomment-582455066 for more information.

**Comment by Amejia481** [comment]
This is ready for QA verification, the changes should be on `main`.

**Comment by lobontiumira** [comment]
Hi Arturo!
This is not fixed yet on the 8.13.1, build #1190.0a1-20210525093431, with Google Pixel (Android 10):


https://user-images.githubusercontent.com/40694158/120792709-9b5ade80-c53e-11eb-8821-0e9a33be2868.mp4

PS: I verified that the build contained these 2 fixes (4864, and 4872):
![main](https://user-images.githubusercontent.com/40694158/120792886-dc52f300-c53e-11eb-88c8-12280c553e0e.jpg)

**Comment by Amejia481** [comment]
Thanks @lobontiumira for testing I will take a look!

**Comment by Amejia481** [comment]
Thanks for testing, to be to see the change you have start with a fresh installation :) 

As we made a changed on the default value of the setting "Block other content trackers" to make it ON by default, for testing you have to start from a fresh installation, as we are not altering the value that users already have for this setting.

If I can help with anything else just let me know, happy to help :)

**Comment by lobontiumira** [comment]
@Amejia481 I've verified again on the 8.13.1, build #1190.0a1-20210525093431 with Samsung Galaxy Note 8 (Android 9) with a clean profile, and it still reproduces.
After the page is loaded, the ads, social and analytics trackers are displayed as "Not blocked" with the default settings. All the Tracking protection toggles are enabled by default. Refreshing the page fixes the issue.
Maybe this logcat helps: [logcat.txt](https://github.com/mozilla-mobile/focus-android/files/6607362/New.Text.Document.txt)
