### ISSUE TITLE
Enabling Tracker protection settings shows the trackers are "not blocked" instead of "blocked"

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/focus-android#4872]
## Steps to reproduce
1. Go to Settings -> Privacy & Security -> Tracking Protection section;
2. Enable analytic trackers, exit Setting;
3. Go to https://senglehardt.com/test/trackingprotection/test_pages.html, and tap on Trackers and Cookies.;
4. Observe the analytics trackers state;
### Expected behavior
The page shows that analytics trackers are "blocked".
### Actual behavior
The page shows that analytics trackers are "not blocked".
### Notes
This is also reproducible for ad trackers, social trackers, other content trackers.
For other content trackers, when enabled, the analytics, ads and analytics trackers are displayed as "blocked".
### Device information

* Android device: Pixel 2 (Android 9)
* Focus version: #1190 dev build from main
* Not reproducible on Focus 8.15.4

**Comment by pocmo** [comment]
@Amejia481 Do you have some time to help us figure this out?

**Comment by Amejia481** [comment]
Sure!

**Comment by Amejia481** [comment]
This will be covered by https://github.com/mozilla-mobile/focus-android/pull/4911.
Just to let you know, there a known bug for fresh installs, where we are not able to block on the first load as it take some time for geckoView to fetch and download the content blocking list, if that happens refreshing should fix the issue and all subsequent loads should be blocked, see https://github.com/mozilla-mobile/fenix/issues/7907#issuecomment-582455066 for more information.

**Comment by Amejia481** [comment]
This is ready for QA verification, the changes should be on `main`.

**Comment by lobontiumira** [comment]
This is not fixed yet. Verified on the 8.13.1, build #1190.0a1-20210525093431, with Google Pixel (Android 10):

https://user-images.githubusercontent.com/40694158/120791482-f12e8700-c53c-11eb-99c3-ee668eaec6eb.mp4


@Amejia481 please review. 
PS: I verified that the build contained these 2 fixes (4864, and 4872):
![main](https://user-images.githubusercontent.com/40694158/120791642-2044f880-c53d-11eb-854c-d640bd463501.jpg)

I'll remove the QAReady label for now.

**Comment by Amejia481** [comment]
As we made a changed on the default value of the setting "Block other content trackers" to make it ON by default, for testing you have to start from a fresh installation, as we are not altering the value that users already have for this setting.

**Comment by lobontiumira** [comment]
I've verified again on the 8.13.1, build #1190.0a1-20210525093431 with Samsung Galaxy Note 8 (Android 9) with a clean profile. 
The setting "Block other content trackers" is ON by default, so the trackers are blocked.

**Comment by sv-ohorvath** [comment]
@Amejia481 sorry to comment so late, I just have a question:
With this fix, everything is blocked by default.
But what if someone turns off "other content trackers" (because it says it could break things in its description)? Will the other 3 categories still be blocked at least partially, since the test page shows that they are not blocked? I don't know how exactly the test page works, I would expect it to show the first 3 categories as "blocked".

**Comment by Amejia481** [comment]
No problem, @sv-ohorvath thanks for the question.

We have two levels of blocking:

- **Content blocking (Most aggressive) :** Resource like JS and images and other files types are blocked from loading. 
- **Cookies blocking (Less aggressive):** Sites are blocked from writing cookies.

When the **"other content trackers"** setting is **ON** it means that we are blocking content on the categories that the user has turned **ON** (`Advertising`, `analytics`, and `social`), on the other hand when the **"other content trackers"** setting is **OFF** we are only **blocking cookies** on the categories the user has turned **ON** (`Advertising`, `analytics`, and `social`) . 

We are always blocking the categories (`Advertising`, `analytics`, and `social`)  that the users indicate, but in different levels, each test page tries to mimic different categories on **blocking content or cookies**.


Hope this help, if you still have any questions, I'm happy to help :)
